### ISSUE TITLE
Failure modes

### ISSUE THREAD

**Issue by jchook** [reactphp/dns#198] opened 2022-04-30 01:33 UTC
I recently had a rare production scenario where a DNS query apparently returned an incorrect successful empty response during the onset of a data center network failure.

I would like to audit the failure modes and ensure that remote failure results in an exception and not a successful empty response.

**Comment by jchook** [comment] 2022-04-30 01:40
Perhaps worth noting that only moments later subsequent DNS responses threw timeout exceptions.

**Comment by WyriHaximus** [comment] 2022-04-30 08:59
> I recently had a rare production scenario where a DNS query apparently returned an incorrect successful empty response during the onset of a data center network failure.

Does this situation involve a hard network cut of the connection with the DNS server that can only be reproduced by pulling the network or power cable of the DNS server? We're looking into a big that involves exactly that and looking into ways how best we can test that.

**Comment by jchook** [comment] 2022-04-30 16:09
The only incident report from the data center suggests the issue may be related to packet loss. https://status.linode.com/incidents/slt7wj3ktrls

Hard to say, though. This report is time stamped at 02:22-04:10 UTC and my incident occurred at 18:00 nearly on the dot.

Linode Newark has connectivity blips nearly every day it seems. You could just loop queries on one of their VPCs lol!

**Comment by WyriHaximus** [comment] 2022-04-30 18:25
Well package loss could resemble a hard connection drop as I described above. Did this only occur once, or did you observe it multiple times?

**Comment by jchook** [comment] 2022-04-30 22:58
I saw one incorrect successful empty response, then several timeout errors.

**Comment by jchook** [comment] 2022-04-30 23:00
My script runs 4 or so checks in parallel at a time.

In the first batch, I saw 3 successful responses with accurate data and 1 incorrect empty response (CNAME).

In the subsequent batches, all requests failed with timeout exceptions.

**Comment by clue** [comment] 2022-05-03 08:22
> I recently had a rare production scenario where a DNS query apparently returned an incorrect successful empty response during the onset of a data center network failure.

@jchook Thank you for reporting, this definitely shouldn't have happened! I wonder what issue you've seen specifically, can you provide more details what "returned an incorrect successful empty response" means?

The DNS protocol defines message formats and semantics. An empty response with an error code of `0` is a perfectly valid message in DNS. This is commonly used to signal that a query for a valid domain does not return any records (such as when using `AAAA` for a domain that has no IPv6 support).

Our low-level `ExecutorInterface` handles this as a `Message` with an empty list of `Record` objects accordingly. The more common higher-level `resolve()` and `resolveAll()` methods on the `ResolverInterface` throw a `RecordNotFoundException` in this case as documented.

> I would like to audit the failure modes and ensure that remote failure results in an exception and not a successful empty response.

I invite you to take a look at the existing test suite which covers all of the above situations and more in greater detail:

* https://github.com/reactphp/dns/blob/2bc106d3055c8b3d267cbbce3f7716d8078c1932/tests/Resolver/ResolverTest.php
* https://github.com/reactphp/dns/blob/2bc106d3055c8b3d267cbbce3f7716d8078c1932/tests/Query/UdpTransportExecutorTest.php
* https://github.com/reactphp/dns/blob/2bc106d3055c8b3d267cbbce3f7716d8078c1932/tests/Query/TcpTransportExecutorTest.php

I hope this helps! I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can always reopen this :+1:

**Closed as completed by clue** 2022-05-03 08:22 UTC
Labels: question

**Comment by jchook** [comment] 2022-05-04 00:39
> ...can you provide more details what "returned an incorrect successful empty response" means?

@clue ReactPHP DNS reported a successful empty response for a CNAME lookup, even though the CNAME RR existed at the time of query and has remained untouched for well over a year.

This led me to believe either:

a. The remote DNS server (1.1.1.1 --> ns1.dreamhost.com) erroneously reported an empty record, or
b. ReactPHP erroneously reported an empty record

While (a) is certainly possible, (b) seemed plausible considering the timing of the data center network outage.

Also it seemed strange that, of the 4 parallel queries to the same nameserver, 3 of them returned correct successful non-empty responses. CNAME was the last to finish and it erroneously reported an empty record. Immediate subsequent queries all failed with a `React\Promise\Timer\TimeoutException`.

> I invite you to take a look at the existing test suite which covers all of the above situations and more in greater detail

Thanks I'll take a look at this more.

**Comment by clue** [comment] 2022-05-04 06:03
> This led me to believe either:
> 
> a. The remote DNS server (1.1.1.1 --> ns1.dreamhost.com) erroneously reported an empty record, or
> b. ReactPHP erroneously reported an empty record
> 
> While (a) is certainly possible, (b) seemed plausible considering the timing of the data center network outage.

I don't currently see how this could be caused by ReactPHP, but I would love to learn more about this situation. Please report back if you happen to find out more details.
