### ISSUE TITLE
Windows Error: DNS query for google.com failed: too many retries

### ISSUE THREAD

**Issue by internalsystemerror** [reactphp/dns#44] opened 2017-01-23 04:41 UTC
The code used is (using v0.4.3):

```php
<?php
// dns.php
error_reporting(PHP_INT_MAX);

require_once 'vendor/autoload.php';

$loop = \React\EventLoop\Factory::create();
$factory = new \React\Dns\Resolver\Factory();
$dns = $factory->create('8.8.8.8', $loop);

$dns->resolve($argv[1])
    ->then(
        function ($ip) { echo "Host: $ip\n"; },
        function ($e) { echo "Error: {$e->getMessage()}\n"; }
);

$loop->run();
```

The command:
```
php dns.php google.com
```

The error:

```
Error: DNS query for google.com failed: too many retries
```

Is there any way I can debug this further to find out what's causing this? The same code on my linux box works just fine...

**Comment by clue** [comment] 2017-01-23 09:37
Thanks for reporting!

What Windows version are you using?
Does the test suite yield any errors?

Perhaps you can try patching the `Executor` class and raise the timeout value and/or patch the `RetryExecutor` and patch the number of retries?

**Comment by WyriHaximus** [comment] 2017-01-23 18:26
Seeing the same error on my windows 10 gaming desktop. One test fails:

```
There was 1 failure:

1) React\Tests\Dns\FunctionalTest::testResolveGoogleResolves
Expectation failed for method name is equal to <string:__invoke> when invoked 1 time(s).
Method was expected to be called 1 times, actually called 0 times.
```

I'll make a PR with AppVeyor configuration, @clue or @cboden could you setup AppVeyor for this repository?

**Comment by internalsystemerror** [comment] 2017-01-23 20:26
Windows 10 + updates (not sure the exact build anymore, it changes without me knowing these days) ... I'll run the test suites when I get back... I'm sure it's probably related to php configuration on windows... One thing I did try already was increasing the timeout and retries already, with same result

**Comment by internalsystemerror** [comment] 2017-01-23 20:39
Confirming that running the testsuite on windows gives the error quoted by @WyriHaximus.

**Comment by uniquoooo** [comment] 2017-01-27 00:44
Windows 10 users of a library I develop are also experiencing this problem, I haven't been able to test as I don't have a Windows 10 machine.

**Comment by kassmed** [comment] 2017-02-03 06:37
I have the same issue on windows server 2008 R2, but that is w7 basically, not w10. Any solution?

**Comment by MrPh1l** [comment] 2017-02-07 02:47
Is anyone working on it?

**Comment by MrPh1l** [comment] 2017-02-07 02:48
Anyone found a temporary way of bypassing this bug?

**Comment by WyriHaximus** [comment] 2017-02-07 08:10
> Anyone found a temporary way of bypassing this bug?

Will try and look into it tonight when I don't forget. Something you could try in the mean time is using your local DNS server (most likely your router) instead of the Google's DNS server (`8.8.8.8` and `8.8.4.4`) or try a different open DNS service like [OpenDNS](https://www.opendns.com/setupguide/) (`208.67.222.222` and `208.67.220.220`)

**Comment by kassmed** [comment] 2017-02-07 08:36
@WyriHaximus Already tried workarounds like that. Doesn't help. It seems to be a problem only on windows though. Setting in system DNS servers, hardcoding DNS servers or even manually inserting the resolved IP in the hosts file does not help the problem.

**Comment by WyriHaximus** [comment] 2017-02-07 09:59
@kassmed Bonkers does UDP work at all on windows? You could use https://github.com/reactphp/datagram/tree/master/examples to test that

**Comment by kassmed** [comment] 2017-02-07 13:38
@WyriHaximus Seems to work fine on localhost, but externally i get the same error. Here is a picture of both runs:
https://gyazo.com/67987ed351262a4aaf505130f38a8e76

**Comment by WyriHaximus** [comment] 2017-02-07 14:08
@kassmed don't let datagram do the DNS look up, provide it an IP instead of a hostname to work around that

**Comment by kassmed** [comment] 2017-02-07 14:31
@WyriHaximus Well now i can make my websocket connect, but now i just have the problem that the CN does not match the certificate when using wss, so the connection handshake fails.

**Comment by kassmed** [comment] 2017-02-07 15:13
@WyriHaximus I managed to make a REALLY dodgy bypass. In react\socket-client\src\SecureConnector.php i found the line:
'peer_name' => $host

Here i just hardcoded the hostname of what i wanted to connect to, but let the socket connect to the IP directly without DNS lookup.

**Comment by kassmed** [comment] 2017-02-07 15:44
@WyriHaximus Well, that fix turned out to not work 100% for me, but it might help someone else.

**Comment by WyriHaximus** [comment] 2017-02-07 16:23
@kassmed on my way home now, will look at it after dinner :smile:

**Comment by WyriHaximus** [comment] 2017-02-07 21:36
@kassmed haven't had any success yet, will keep trying the rest of the week. Can reproduce the results in native git and the ubuntu sub system on windows. But it's working fine from within a vagrant box on the same machine.

**Comment by Jimmy062006** [comment] 2017-02-11 23:26
No idea if this helps at all.

http://pastebin.com/ZKFaPauu

**Comment by Jimmy062006** [comment] 2017-02-12 14:38
Does the request look like its formatted correctly in my pastebin ?

**Comment by clue** [comment] 2017-02-13 07:43
Thanks for digging into this @micksam7! :+1: 

Does anybody feel like filing a PR to fix this for this component in the meantime? :shipit: 

Also, this should ultimately be fixed via #12 instead.

**Comment by Jimmy062006** [comment] 2017-02-13 09:12
Testing buffersize fix on a windows machine now.

**Comment by Jimmy062006** [comment] 2017-02-14 10:02
PR made https://github.com/reactphp/stream/pull/65

**Comment by internalsystemerror** [comment] 2017-02-14 14:52
@micksam7 Thank you! Been struggling to figure that out, I guess I just assume PHP works flawlessly :/
@Jimmy062006 Thanks for the fix also!

**Comment by TheMeq** [comment] 2017-03-02 14:11
Note: Issue also affects Windows Server 2012 R2.

**Comment by clue** [comment] 2017-03-09 12:21
Closed via #53

**Closed by clue** 2017-03-09 12:21 UTC
Labels: bug, help wanted

**Comment by ScorpioKC** [comment] 2018-02-20 03:17
I'm having the very same problem on my phone.Operating system is Android 7.0

**Comment by clue** [comment] 2018-02-20 07:55
@ScorpioKC We're not aware of any issues currently. Can you give some instructions on how to reproduce the problem you're seeing? Also, output of `php -v` and `composer info` would help :+1:

**Comment by Sonus2021** [comment] 2019-06-02 20:00
9833a7395829bb4e2d56.js:108 WebSocket connection to 'wss://gateway.discord.gg/?encoding=etf&v=6&compress=zstd-stream' failed: Error during WebSocket handshake: Unexpected response code: 520 An ideas
![image](https://user-images.githubusercontent.com/51299491/58766690-5e664680-8536-11e9-8065-3042b8011d38.png)
